var tweets = [
  {
    "tweet_datetime_str": "2025-11-03 18:16",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.dhLW.dhLW.dhLW.dhqm.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.cR2I.dJfu.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.dhqc.dhqc.dhqc.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.cph0.cxFE.cxFE.cxFE.cpwe.cpwe.cpwe.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "人形Nm",
    "tmatch": "denbudenbu1/1985274818338685382",
    "twname": "でんぶ",
    "twitter_id": "@denbudenbu1",
    "twtext": "人形ネメシスでビヨンド達成<br><br>ビィくんが進化権使わずに動けるのと超進化使わずにグラン＆ジータ7t起動できたりして偉かったです。",
    "image_links": "https://pbs.twimg.com/media/G40cF5YaUAAuX79?format=jpg&name=small,https://pbs.twimg.com/media/G40cF5WasAAvrTQ?format=jpg&name=small",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 18:07",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dO4Y.cc--.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.cdTm.cdTm.cdTm.dOYO.dOYO.dOYO.dhqc.dhqc.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "KobaBanZ/1985272514533298295",
    "twname": "ちゃんこば",
    "twitter_id": "@KobaBanZ",
    "twtext": "財宝ロイヤルでビヨンド！！！<br>石板置いてる余裕を感じないのでグラン＆ジータ入れて好感触！！",
    "image_links": "https://pbs.twimg.com/media/G40aXPWbsAAcCHj?format=jpg&name=small,https://pbs.twimg.com/media/G40aYlKboAAqswA?format=jpg&name=360x360,https://pbs.twimg.com/media/G40ag2zbUAEmMQX?format=jpg&name=240x240",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 17:54",
    "class_no": 5,
    "deck_code": ".cM8E.cM8E.cM8E.dhqm.dhqm.dhqm.ckYk.ckYk.ckYk.dtYc.dtYc.dtYc.d6mk.d6mk.d6mk.d70M.d70M.d70M.dtoO.dtoO.dtoO.dhqc.dhqc.dhqc.dVNk.dVNk.dVNk.di4E.di4E.du1s.du1s.du1s.cl28.cl28.duHU.duHU.duHU.duHe.duHe.duHe",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "進化Ni",
    "tmatch": "ion05155544/1985269307685953964",
    "twname": "マイナスion",
    "twitter_id": "@ion05155544",
    "twtext": "グラマスの後5連勝でEPIC到達！！！<br>進化ナイトメア安定感あって強い！",
    "image_links": "https://pbs.twimg.com/media/G40X6FAaYAA2pRM?format=jpg&name=small,https://pbs.twimg.com/media/G40X6FEaIAAFVwt?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-03 17:47",
    "class_no": 4,
    "deck_code": ".dhqm.dhqm.dhqm.d50E.d50E.d50E.d4KU.d4KU.d4KU.ciMG.ciMG.ciMG.dSxe.dSxe.dSxe.cJl6.cJl6.cJl6.dhqc.dhqc.dhqc.dTQu.dTQu.dTQu.drrO.drrO.drrO.cibu.cibu.cibu.cxFE.cxFE.cxFE.drrE.drrE.drrE.cic2.cic2.cic2.dTQk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "疾走ランプD",
    "tmatch": "chirokirochiron/1985267535940550724",
    "twname": "Chiron / キロン",
    "twitter_id": "@chirokirochiron",
    "twtext": "疾走ドラでEPIC<br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G40WTR9aAAA2IyS?format=jpg&name=small,https://pbs.twimg.com/media/G40WTR6bYAAH2BN?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-03 17:37",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cwl-.cwl-.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dpCU.dpCU.dpCU.dJfu.cfjM.cfjM.cfjM.dhqc.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.dovu.dovu.dovu.di4E.di4E.d2a8.d2a8.d2a8.d2Z-.d2Z-.d2Z-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "秘術W",
    "tmatch": "5150_15/1985265163298283678",
    "twname": "5150",
    "twitter_id": "@5150_15",
    "twtext": "秘術ウィッチでビヨンド到達ー<br>チェレッタ入れると唯一の守護ノーマンを押し付けに使えるのが偉い<br>財宝と当たって喜べる最高のデッキ",
    "image_links": "https://pbs.twimg.com/media/G40TVyNagAAGpix?format=jpg&name=small,https://pbs.twimg.com/media/G40TXUBawAEJszi?format=jpg&name=small",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 17:37",
    "class_no": 6,
    "deck_code": ".cmmw.cmmw.cmmw.dXaM.dXaM.cxFO.cxFO.cxFO.dJfu.dJfu.dJfu.dXp-.dXp-.cn0i.cn0i.dXrY.dXrY.dwVg.dwVg.dwVg.dYJO.dYJO.dYJO.dXdU.dXdU.dXdU.dY5A.dY5A.dY5A.dY3c.dY3c.dY3c.d9uu.d9uu.d9uu.cnGK.cnGK.cnGK.cnUE.cnUE",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "クレストB",
    "tmatch": "1nCRzIHzQnImV95/1985265026861760530",
    "twname": "AlmostCarry シャドバ",
    "twitter_id": "@1nCRzIHzQnImV95",
    "twtext": "まだEPICになったばかりの印象<br>クレストビショップ序盤から中盤のテンポロスが大きく6.7ターン目の動きが窮屈<br><br>2ターン目の動きがないことによるテンポロスで押され続けるので、2コスを試したが微妙で5ターン目の団結マーを弾きに行く方が強い。<br>ロデオ濁るが教会採用　レフィーエが神<img src=\"https://abs-0.twimg.com/emoji/v2/svg/2b55.svg\"/><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G40UBLka4AAcY6K?format=jpg&name=small,https://pbs.twimg.com/media/G40UBLfbkAEP113?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-03 17:22",
    "class_no": 5,
    "deck_code": ".dhqm.dhqm.dhqm.cLuw.cLuw.cLuw.ckrU.ckrU.ckrU.d6mk.d6mk.d6mk.dJfu.dJfu.d6zE.d6zE.d6zE.dtoY.dtoY.dVNk.dVNk.dVNk.cl2I.cl2I.cl2I.dVdM.dVdM.dVdM.d6zO.d6zO.d6zO.cxFE.cxFE.cxFE.dVt8.dVt8.dVt8.cl1-.cl1-.cl1-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "ミッドレンジNi",
    "tmatch": "1OVJmbbp7ZEpJYp/1985261163752661184",
    "twname": "カワイ",
    "twitter_id": "@1OVJmbbp7ZEpJYp",
    "twtext": "ミッドレンジナイトメアでとりあえずEPIC来た！<br>デッキはグラマス昇格の時から1枚変更<br>・バアル1 ⇒ ギルネ1<br><br>グラマスになってから10戦位したんだけど、ロイヤル少し多めで、やってる中で回復プランも「行ける時は行ける」の感覚が少しあったため変更<br><br>ただ一長一短だから好きな方でいいとは思う",
    "image_links": "https://pbs.twimg.com/media/G40Pg0ka8AAmYQd?format=jpg&name=small,https://pbs.twimg.com/media/G40P1IWbgAA42VK?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-03 17:09",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cfQm.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dQ-U.dQ-U.dQ-U.dpCU.dpCU.dpCU.cfjM.cfjM.cfjM.dhqc.dhqc.dhqc.cfwA.cfwA.dpP8.dpP8.dpP8.dovu.dovu.dovu.di4E.di4E.d2a8.d2a8.d2a8.d2Z-.d2Z-.dQ-e.dQ-e",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "秘術W",
    "tmatch": "AAAAAAAAAAA1A1A/1985257988932907402",
    "twname": "^_^@シャドバよう",
    "twitter_id": "@AAAAAAAAAAA1A1A",
    "twtext": "ヴェハリヤー入り秘術でBeyondタッチ<br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G40NnjEaUAA0xmy?format=jpg&name=small,https://pbs.twimg.com/media/G40NnjFb0AAhmkl?format=jpg&name=small",
    "rating": 1862
  },
  {
    "tweet_datetime_str": "2025-11-03 16:58",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.cc--.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.dJRg.cdTm.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "財宝R",
    "tmatch": "inorderWB/1985255300317040894",
    "twname": "整理整頓",
    "twitter_id": "@inorderWB",
    "twtext": "財宝ロイヤルで15連勝(マスター帯10、グラマス帯5)<br>そしてエピックも到達<img src=\"https://abs-0.twimg.com/emoji/v2/svg/270c.svg\"/>　<br>侍の性能好きだけどなくても良さげ<br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a><br><a href=\"https://x.com/hashtag/シャドバ勢と繋がりたい?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバ勢と繋がりたい</a>",
    "image_links": "https://pbs.twimg.com/media/G40LKhRbcAAdw_A?format=jpg&name=small,https://pbs.twimg.com/media/G40LKhvbMAAb8Vd?format=jpg&name=240x240,https://pbs.twimg.com/media/G40LKjbaoAE4oSe?format=jpg&name=240x240",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-03 16:47",
    "class_no": 4,
    "deck_code": ".dTEE.dTEE.dhqm.dhqm.dhqm.d50E.d50E.d50E.d4KU.d4KU.d4KU.ciMG.ciMG.dSxe.dSxe.cJl6.cJl6.cJl6.dhqc.dhqc.d4X8.d4X8.dTQu.dTQu.dTQu.drrO.drrO.drrO.cibu.cibu.cxFE.cxFE.d4mc.d4mc.drrE.drrE.cic2.cic2.dTQk.ciM6",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "疾走ランプD",
    "tmatch": "WZVYNB6xdTq97dI/1985252502045159809",
    "twname": "ののの",
    "twitter_id": "@WZVYNB6xdTq97dI",
    "twtext": "7連勝で初BEYOND達成！！！！！！瞬間3位！<br>ドラゴン最強！！！",
    "image_links": "https://pbs.twimg.com/media/G40HORZbsAARpOo?format=jpg&name=240x240,https://pbs.twimg.com/media/G40HORZbcAAwst8?format=jpg&name=240x240,https://pbs.twimg.com/media/G40HORbbAAAWL0l?format=jpg&name=240x240,https://pbs.twimg.com/media/G40HepCbIAAT8ID?format=jpg&name=240x240",
    "rating": 1862
  },
  {
    "tweet_datetime_str": "2025-11-03 16:42",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfQm.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dpCU.dpCU.dpCU.dJfu.cfjM.cfjM.cfjM.dhqc.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.dovu.dovu.dovu.di4E.d2a8.d2a8.d2a8.cxFE.d2Z-.d2Z-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "秘術W",
    "tmatch": "shinyora__/1985251299689160893",
    "twname": "えりるちゃん",
    "twitter_id": "@shinyora__",
    "twtext": "とりま秘術ウィッチでエピック！<br>かなりに沼って試行錯誤してリストは今これがいい感じ",
    "image_links": "https://pbs.twimg.com/media/G40GsGyakAAnQcu?format=jpg&name=small,https://pbs.twimg.com/media/G40GtSSakAANDRH?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-03 16:30",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dQ-U.dQ-U.dpCU.dpCU.dpCU.dJfu.dJfu.cfjM.cfjM.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.d1uE.d1uE.dovu.dovu.dovu.di4E.di4E.d2a8.d2a8.d2a8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "秘術W",
    "tmatch": "gotcoppu/1985248179382812755",
    "twname": "神コップ＠9/26動画投稿",
    "twitter_id": "@gotcoppu",
    "twtext": "ララアンセム抜き秘術ウィッチにしてからずっと勝ってる。5連勝。EPICにもいけました。<br>このままビヨンド目指すのか？？？<br>前のターンで盤面ガラ空きで返して相手はドレイン先が無くて勝ち。<br>ララアンセムだとドレインされ放題だったから明確に強いところ出た。",
    "image_links": "https://pbs.twimg.com/media/G40ErRIbcAE-Lhv?format=jpg&name=240x240,https://pbs.twimg.com/media/G40ErRHaEAAhFLH?format=jpg&name=240x240,https://pbs.twimg.com/media/G40ErRDawAAbNBd?format=jpg&name=240x240,https://pbs.twimg.com/media/G40ErRHa0AAI-Zn?format=jpg&name=240x240",
    "rating": 1655
  },
  {
    "tweet_datetime_str": "2025-11-03 16:29",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dpCU.dpCU.dpCU.dJfu.dJfu.cfjM.cfjM.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.cg9e.cg9e.cg9e.dovu.dovu.d2a8.d2a8.d2a8.cxFE.cxFE.cxFE.d2Z-.d2Z-.d2Z-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "秘術W",
    "tmatch": "uruna_u67/1985247861060338173",
    "twname": "うるな",
    "twitter_id": "@uruna_u67",
    "twtext": "秘術ウィッチでULTIMATE来たー！！！<br>1600からULTIMATEまで14戦12勝2敗だったんだけど最強か！？<br>前シーズンはきつかった人形ネメシスにも押し勝ててパワーめっちゃ感じる！<br>この勢いでBEYOND目指すぞー！！！",
    "image_links": "https://pbs.twimg.com/media/G40DsT0bYAAuwLw?format=jpg&name=small,https://pbs.twimg.com/media/G40DtJbaoAAcCi7?format=jpg&name=small",
    "rating": 1750
  },
  {
    "tweet_datetime_str": "2025-11-03 15:56",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.cR2I.dJfu.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.dyR6.dyR6.dyR6.dhqc.dhqc.da3k.dCK-.dCK-.dCK-.cpRY.cpRY.dyzU.dyzU.dyzU.cxFE.cxFE.cxFE.cpwe.cpwe.cpwe.cphA",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "人形Nm",
    "tmatch": "stella04196009/1985239745358950861",
    "twname": "stella",
    "twitter_id": "@stella04196009",
    "twtext": "初ビヨンド到達とネメシスランキング瞬間1位！<br>グラマス上がってからはずっとこのレシピで人形ネメシス使ったけど強かった！<br>とりあえず2000目指します<img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f44d.svg\"/><br><a href=\"https://x.com/hashtag/シャドバBW?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバBW</a>",
    "image_links": "https://pbs.twimg.com/media/G4z9BQeasAAICuq?format=jpg&name=small,https://pbs.twimg.com/media/G4z9BQfbAAARxII?format=jpg&name=small",
    "rating": 1911
  },
  {
    "tweet_datetime_str": "2025-11-03 14:53",
    "class_no": 5,
    "deck_code": ".ckME.dVs-.dVs-.dVs-.d70M.d70M.d70M.dVPI.dVPI.dVPI.dJfu.dV86.dV86.dV86.dtoY.dtoY.dtoY.dVgU.dVgU.dVgU.dhqc.dhqc.dhqc.dVNk.dVNk.dVNk.dVdM.dVdM.dVdM.di4E.cYqk.dVt8.dVt8.dVt8.duHU.duHU.duHe.d7SU.d7SU.d7SU",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "モードNi",
    "tmatch": "zyasunn/1985223744152051719",
    "twname": "じゃすん＠シャドバVT　固定コメビヨンド達成ミッド解説動画",
    "twitter_id": "@zyasunn",
    "twtext": "ネクロ１位の座を奪還したぜ<br>完全に財宝メタりに行ってる感じ<br>守護ビショ皆無だから達するさん解雇の危機<br>サンダルは何もない場所から２点回復生えてきたり<br>不利対面の進化ネクロに１０点不意打ちで叩き込んだり<br>でなくはない・・・？ってところ",
    "image_links": "https://pbs.twimg.com/media/G4zuFvqbUAAkqBz?format=jpg&name=small,https://pbs.twimg.com/media/G4zuGUDboAAObCY?format=jpg&name=small",
    "rating": 1935
  },
  {
    "tweet_datetime_str": "2025-11-03 14:43",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.cR2I.cR2I.cR2I.dJfu.dJfu.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.dhqc.dhqc.dhqc.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.dyzU.dyzU.cxFE.cxFE.cpwe.cpwe.cpwe.cphA.cphA",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "人形Nm",
    "tmatch": "sokkun123123/1985221358171959371",
    "twname": "そっくん",
    "twitter_id": "@sokkun123123",
    "twtext": "人形ネメシスでグラマスとEPICに到達<br>めっちゃ勝てるけど正直新カードの強さはそこそこ<br>ララアンセムはオーキス人形で楽に処理できるし今の環境にあってるのが大きいのかも",
    "image_links": "https://pbs.twimg.com/media/G4zsTfFasAAUhO8?format=jpg&name=small,https://pbs.twimg.com/media/G4zsTfGbMAA9qMY?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zsThaaIAA6KUL?format=jpg&name=240x240",
    "rating": 1659
  },
  {
    "tweet_datetime_str": "2025-11-03 14:39",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dQ-U.dQ-U.dpCU.dpCU.dpCU.dJfu.dJfu.cfjM.cfjM.cfjM.dhqc.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.dovu.dovu.dovu.di4E.di4E.d2a8.d2a8.d2a8.d2Z-.d2Z-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "秘術W",
    "tmatch": "CASTER_ebibkw/1985220160962363576",
    "twname": "海老原 悠",
    "twitter_id": "@CASTER_ebibkw",
    "twtext": "秘術ウィッチでBEYONDに達した！！<br>ヴェハリヤーが現環境のメタカードとしてもサンダルフォンリーサルの時も使い勝手良くて味<br>ララアンセムの通りが悪い対面は進化稼いでサンダルフォンで<img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f44a.svg\"/><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4zrNsYbwAA6OnZ?format=jpg&name=small,https://pbs.twimg.com/media/G4zrNsXbEAAgFXq?format=jpg&name=small",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 14:26",
    "class_no": 4,
    "deck_code": ".dhqm.dhqm.d50E.d50E.d50E.d4KU.d4KU.d4KU.ciMG.ciMG.ciMG.dSxe.dSxe.dSxe.cJl6.cJl6.cJl6.dhqc.dhqc.dhqc.dTQu.dTQu.dTQu.drrO.drrO.drrO.cibu.cibu.cibu.d4mc.drrE.drrE.drrE.cic2.cic2.cic2.dTQk.dTQk.ciM6.ciM6",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "疾走ランプD",
    "tmatch": "fumi_yosoro/1985216948268138563",
    "twname": "ふみ",
    "twitter_id": "@fumi_yosoro",
    "twtext": "ドラゴンレート瞬間1位きちゃあ！<br>財宝増えたのでネプを入れました",
    "image_links": "https://pbs.twimg.com/media/G4zoScqbwAALOZ4?format=jpg&name=small,https://pbs.twimg.com/media/G4zoScdbEAAyJSL?format=jpg&name=small",
    "rating": 1863
  },
  {
    "tweet_datetime_str": "2025-11-03 14:23",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.cYb6.cYb6.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.dBrk.cR2I.cR2I.cR2I.dJfu.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.dyR6.dhqc.dhqc.dhqc.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.cxFE.cxFE.cpwe.cpwe.cpwe.cphA.cphA.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "人形Nm",
    "tmatch": "koutarouliszt/1985216202516640195",
    "twname": "koutarou",
    "twitter_id": "@koutarouliszt",
    "twtext": "人形ネメシス3位<img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f949.svg\"/><br><br>ショウとかいうカードが打点になるし除去もしてくれるし、ヘイトも集めてくれる神カード！<br><br>ただ3積みは腐ってたから1.2枚でいいイメージだった！<a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4znnRSaAAAJSln?format=jpg&name=small,https://pbs.twimg.com/media/G4znnRKaUAAz3Jl?format=jpg&name=240x240,https://pbs.twimg.com/media/G4znnROb0AAFg2t?format=jpg&name=240x240",
    "rating": 1883
  },
  {
    "tweet_datetime_str": "2025-11-03 14:20",
    "class_no": 1,
    "deck_code": ".cCNE.cCNE.cCNE.canu.canu.canu.cabE.cabE.cabE.cC7c.cC7c.cC7c.caY6.caY6.caY6.czCO.czCO.czCO.dkJ-.dkJ-.dkJ-.cb1q.cb1q.cb1q.dJfk.dJfk.dJfk.czRs.czRs.czRs.czhU.czhU.cbG-.cbG-.cbG-.cxFE.cxFE.cb1g.cb1g.cb1g",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "テンポE",
    "tmatch": "geotaxiss/1985215465300562030",
    "twname": "geotaxis",
    "twitter_id": "@geotaxiss",
    "twtext": "エルフの最速beyond＆最高レート帯で10連勝きたー！　テンポエルフです",
    "image_links": "https://pbs.twimg.com/media/G4zmjLKaAAAAQQc?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zmkWZaMAAw_rq?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zmlRAaAAEJtJb?format=jpg&name=360x360,https://pbs.twimg.com/media/G4zmmcnbQAA7C52?format=jpg&name=240x240",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 14:13",
    "class_no": 5,
    "deck_code": ".cM8E.cM8E.ckME.ckYk.ckYk.ckYk.d6mk.d6mk.d6mk.d70M.d70M.d70M.dJfu.dJfu.dVgU.dVgU.dVgU.ckaI.ckaI.dhqc.dhqc.dhqc.ckog.ckog.dVNk.dVNk.dVNk.di4E.di4E.di4E.dtYm.dtYm.du1s.du1s.du1s.cYqk.duHU.duHU.duHU.duHe",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "進化Ni",
    "tmatch": "hanabishi_0324/1985213725260054677",
    "twname": "花火",
    "twitter_id": "@hanabishi_0324",
    "twtext": "進化ナイトメア バザラガサンダルフォンでビヨンド<br>ウィッチとナイトメアにバザラガが強くて、バザラガと相性が良くロイヤルに強いギルネ、オリヴィエを積みやすいのが良い <br>サンダルフォンでゲームを決めに行くためにがしる",
    "image_links": "https://pbs.twimg.com/media/G4zlQkUbQAAvuFU?format=jpg&name=small,https://pbs.twimg.com/media/G4zlRcdbIAAAoY2?format=jpg&name=small",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 14:09",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.dQ-U.dQ-U.dpCU.dpCU.dpCU.dJfu.cfjM.cfjM.cfjM.dhqc.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.dpP8.dpP8.dpP8.dovu.dovu.dovu.di4E.di4E.d2a8.d2a8.d2a8.d2Z-.d2Z-.d2Z-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "秘術W",
    "tmatch": "KameT5UK1/1985212682220515612",
    "twname": "たーとる",
    "twitter_id": "@KameT5UK1",
    "twtext": "ヴェハリヤー採用秘術ウィッチで<br>11連勝10連勝の21-1でビヨンド！<br>ocs当落までツイート待とうか悩んだけど、自分史上一番勝て嬉しいから投稿。<br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4zkaYFaoAENfaE?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zjiN_aUAE3v1f?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zjkcKbYAEln0U?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zjli2aYAAhUYV?format=jpg&name=240x240",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 13:41",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.dhqm.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.dBrk.dBrk.cR2I.cR2I.cR2I.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.dhqc.dhqc.dhqc.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.cxFE.cxFE.cxFE.cpwe.cpwe.cpwe.dzA8.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "人形Nm",
    "tmatch": "Origami_sv/1985205546698657990",
    "twname": "折り紙",
    "twitter_id": "@Origami_sv",
    "twtext": "人形ネメシスでBEYOND達成～<br>構築はすだれさん（<a href=\"https://x.com/mizutan521913\" style=\"color: rgb(29, 155, 240);\">@mizutan521913</a>)のリストを参考にしました！！！<br>財宝ロイヤル以外の全部と戦える神デッキ！<br><br>愛",
    "image_links": "https://pbs.twimg.com/media/G4zdxZqakAAAPgX?format=jpg&name=small,https://pbs.twimg.com/media/G4zdyN_aEAA4-CM?format=jpg&name=small",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 13:37",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dpCU.dpCU.dpCU.dJfu.dJfu.cfjM.cfjM.cfjM.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.cfvs.cfvs.dovu.dovu.dovu.di4E.di4E.d2a8.d2a8.d2a8.cxFE.d2Z-.d2Z-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "秘術W",
    "tmatch": "pero_svwb/1985204659376853428",
    "twname": "ぺろぺろ@シャドバWB",
    "twitter_id": "@pero_svwb",
    "twtext": "エピックスレスレくらいから8連勝であっという間にアルティメット〜！！！<br>道中で仮想敵の人形とロイヤルもしばけて気持ち良すぎる",
    "image_links": "https://pbs.twimg.com/media/G4zdHZBbgAAW-O3?format=jpg&name=small,https://pbs.twimg.com/media/G4zdHY_bAAA0G-T?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zdHY8awAEppow?format=jpg&name=240x240",
    "rating": 1750
  },
  {
    "tweet_datetime_str": "2025-11-03 13:32",
    "class_no": 4,
    "deck_code": ".dTEE.dTEE.dhqm.dhqm.d50E.d50E.d50E.d4KU.d4KU.d4KU.ciMG.ciMG.ciMG.dSxe.dSxe.dSxe.cJl6.cJl6.cJl6.dTQu.dTQu.dTQu.drrO.drrO.drrO.cibu.cibu.cibu.cxFE.cxFE.drrE.drrE.drrE.cic2.cic2.cic2.dTQk.dTQk.ciM6.ciM6",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "疾走ランプD",
    "tmatch": "Rin_mofv/1985203477568733409",
    "twname": "Rin†rin│りん*",
    "twitter_id": "@Rin_mofv",
    "twtext": "疾走ドラゴンで人生初のBEYOND到達しました<img src=\"https://abs-0.twimg.com/emoji/v2/svg/203c.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/203c.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/203c.svg\"/><br>40枚全部最強です<img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f44a.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f44a.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f44a.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f44a.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f44a.svg\"/><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a> <a href=\"https://x.com/hashtag/シャドバ勢と繋がりたい?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバ勢と繋がりたい</a>",
    "image_links": "https://pbs.twimg.com/media/G4zcB1qboAABcHV?format=jpg&name=small,https://pbs.twimg.com/media/G4zcB1nbkAAuLZm?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zcB1uaIAAqEDO?format=jpg&name=240x240",
    "rating": 1858
  },
  {
    "tweet_datetime_str": "2025-11-03 13:24",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dO4Y.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.dJRg.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "tr72b9o/1985201339371254102",
    "twname": "ペンタん",
    "twitter_id": "@tr72b9o",
    "twtext": "財宝ロイヤルで瞬間1位＆11連勝達成！！！<br>前期から財宝強かったけど今期はゼタ＆ベアトリクスの追加でかなり打点量増えた気がする<br>ワルツ2枚懐疑的だったけど財宝ロイヤルというデッキが強すぎて2枚にしても特に問題なく回せました。<br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4zaF0aasAAbTGU?format=jpg&name=small,https://pbs.twimg.com/media/G4zaF0TaEAAj7Dx?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zaF0cbkAEPExW?format=jpg&name=240x240",
    "rating": 1932
  },
  {
    "tweet_datetime_str": "2025-11-03 13:12",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.cc--.cdTm.cdTm.cdWk.cdjE.cdjE.cdjE.cdjY.cxFE.cxFE.dJRg.dJRg.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dO4Y.dO4Y.dOIc.dOIc.dOIc.dOLk.dOLk.dOLk.dOYE.dOYE.dOYE.dOYO.dOYO.dOYO.dmj6.dmmE.dmyk.dmyk.dmyk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "yuyujitekist/1985198445720948897",
    "twname": "YuYu",
    "twitter_id": "@yuyujitekist",
    "twtext": "財宝ロイヤル 瞬間beyond",
    "image_links": "https://pbs.twimg.com/media/G4zXcWHbcAAjV-i?format=jpg&name=small,https://pbs.twimg.com/media/G4zXcWDbYAA2ZXC?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zXcWBbIAALDwg?format=jpg&name=240x240",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 12:37",
    "class_no": 7,
    "deck_code": ".cpEu.cpEu.cpEu.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.dyRQ.dyRQ.dyRQ.daY-.daY-.daY-.daHo.daHo.daHo.dJfu.dJfu.dJfu.cpwU.cpwU.cpwU.dalU.dalU.dalU.dale.dale.dale.dywM.dywM.dywM.daVs.daVs.daVs.dzA8.dzA8.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "リーシェナNm",
    "tmatch": "earman178/1985189584087769094",
    "twname": "エアーマン@Vtuber【シャドバWB配信】",
    "twitter_id": "@earman178",
    "twtext": "AF破壊ネメシスで5連勝EPIC<img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f44f.svg\"/>",
    "image_links": "https://pbs.twimg.com/media/G4zPZUPbMAAhx91?format=jpg&name=small,https://pbs.twimg.com/media/G4zPZVubYAA--b2?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zPZVracAAOpvM?format=jpg&name=240x240",
    "rating": 1657
  },
  {
    "tweet_datetime_str": "2025-11-03 12:18",
    "class_no": 4,
    "deck_code": ".dhqm.dhqm.dhqm.d50E.d50E.d50E.d4KU.d4KU.d4KU.ciMG.ciMG.ciMG.dSxe.dSxe.dSxe.cJl6.cJl6.cJl6.dhqc.dhqc.dhqc.dTQu.dTQu.dTQu.drrO.drrO.drrO.cibu.cibu.cibu.drrE.drrE.drrE.cic2.cic2.cic2.dTQk.dTQk.ciM6.ciM6",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "疾走ランプD",
    "tmatch": "chopstics0/1985184835103830285",
    "twname": "はし",
    "twitter_id": "@chopstics0",
    "twtext": "GrandeさんのリストでドラゴンULTIMATE到達＆38位！<br>今期はルリアでリソース補給できて安定感UP！",
    "image_links": "https://pbs.twimg.com/media/G4zLDKibYAAXuC-?format=jpg&name=small,https://pbs.twimg.com/media/G4zLEGfasAAzMVo?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zLFOob0AAH93O?format=jpg&name=240x240",
    "rating": 1751
  },
  {
    "tweet_datetime_str": "2025-11-03 11:49",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dhqm.dhqm.dhqm.cdEI.cdEI.cdEI.dNpM.dNpM.dNpM.cxFO.cxFO.cdTm.cdTm.cdTm.dhqc.dhqc.cdTw.cdTw.cdTw.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.cxFE.cxFE.cxFE.cdWk.cdWk.cEaA",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "アグロR",
    "tmatch": "mi2boshi/1985177454705877500",
    "twname": "卒中",
    "twitter_id": "@mi2boshi",
    "twtext": "超最新型‘‘卒中式アグロロイヤル‘‘で6連勝してﾋﾞﾖﾝﾄﾞ到達！！<br>最高グラマス帯９連勝で試合も爆速で終わるからガチで強い<br>久々に好感触なデッキで戦えてめっちゃ楽しい！！<br><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4zDHwXaoAA7dmH?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zDIqbbkAA7Q5q?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zDJcXacAAemtx?format=jpg&name=240x240,https://pbs.twimg.com/media/G4zDKRobkAAgz2n?format=jpg&name=240x240",
    "rating": 1856
  },
  {
    "tweet_datetime_str": "2025-11-03 10:55",
    "class_no": 5,
    "deck_code": ".dhqm.dhqm.dhqm.cLuw.cLuw.cLuw.ckrU.ckrU.ckrU.d6mk.d6mk.d6mk.dJfu.dJfu.dJfu.d6zE.d6zE.dtoY.dtoY.dVNk.dVNk.dVNk.cl2I.cl2I.cl2I.dVdM.dVdM.dVdM.dtYm.dtYm.dtYm.cxFE.cxFE.cxFE.dVt8.dVt8.dVt8.cl1-.cl1-.cl1-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "ミッドレンジNi",
    "tmatch": "match_match99/1985163864791785723",
    "twname": "まっち",
    "twitter_id": "@match_match99",
    "twtext": "とりあえずultimateまできた<br>オーディンが痛いけど、進化メアと秘術に置ければほぼ負けないバザラガが結構強い",
    "image_links": "https://pbs.twimg.com/media/G4y4A1QbcAAdomh?format=jpg&name=small,https://pbs.twimg.com/media/G4y4A1JaIAA1rTg?format=jpg&name=small",
    "rating": 1750
  },
  {
    "tweet_datetime_str": "2025-11-03 09:12",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfQm.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dpCU.dpCU.dpCU.cfjM.cfjM.dhqc.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.dovu.dovu.dovu.di4E.di4E.d2a8.d2a8.d2a8.cxFE.d2Z-.d2Z-.dQ-e",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "秘術W",
    "tmatch": "mmm29432943/1985137976981278770",
    "twname": "えむ@月と太陽実装待ち",
    "twitter_id": "@mmm29432943",
    "twtext": "ビヨンドだ〜！いろんなクラスやったけど、秘術がつよつよ〜。",
    "image_links": "https://pbs.twimg.com/media/G4ygdx7bAAAIgsa?format=jpg&name=small,https://pbs.twimg.com/media/G4ygd1ba0AEMOSh?format=jpg&name=240x240,https://pbs.twimg.com/media/G4ygd1fbQAAL7bh?format=jpg&name=240x240",
    "rating": 1858
  },
  {
    "tweet_datetime_str": "2025-11-03 09:04",
    "class_no": 7,
    "deck_code": ".dhqm.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.daY-.daY-.daY-.daHo.daHo.daHo.dJfu.dJfu.dJfu.dalU.dalU.dalU.dyjs.dyjs.dhqc.dhqc.dhqc.dale.dale.dale.cph0.cph0.daVs.daVs.daVs.dyzU.cxFE.cxFE.cxFE.dzA8.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "リーシェナNm",
    "tmatch": "kanossanoku/1985135978034626691",
    "twname": "カノッサ",
    "twitter_id": "@kanossanoku",
    "twtext": "フルプレにしたので再掲。アルティメット到達、破壊ネメシス。俺のプレミアムのチームシェナたそみてくれ",
    "image_links": "https://pbs.twimg.com/media/G4yepTCbcAAVsWM?format=jpg&name=small,https://pbs.twimg.com/media/G4yepTGaMAArfEs?format=jpg&name=small",
    "rating": 1756
  },
  {
    "tweet_datetime_str": "2025-11-03 08:44",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dO4Y.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.dJRg.cdTm.cdTm.cdTm.dOYO.dOYO.dOYO.cdTw.dOIc.dOIc.dOIc.dmyk.dmyk.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "karakuri900/1985131041607262699",
    "twname": "のみず",
    "twitter_id": "@karakuri900",
    "twtext": "蒼空の六龍環境<br>財宝ロイヤルで早めのグラマス到達でビヨンドも達成<br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4yaJLnaIAAGVXN?format=jpg&name=240x240,https://pbs.twimg.com/media/G4yaJLtaoAA23Rx?format=jpg&name=240x240,https://pbs.twimg.com/media/G4yaJLsaAAAv5o7?format=jpg&name=240x240,https://pbs.twimg.com/media/G4yaJLna8AAzzJ5?format=jpg&name=240x240",
    "rating": 1859
  },
  {
    "tweet_datetime_str": "2025-11-03 08:28",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dO4Y.cc--.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.dJRg.cdTm.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "glass3689/1985126980917010893",
    "twname": "硝子",
    "twitter_id": "@glass3689",
    "twtext": "高レートの財宝ミラー2連戦勝利でCR全体で1位！！<br>シャドバ上手くなったと思わせてくれるレベルで馬鹿みたいに勝てる財宝ロイに感謝<br><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a> <a href=\"https://x.com/hashtag/シャドバ?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバ</a>",
    "image_links": "https://pbs.twimg.com/media/G4yVW8hbwAAUISB?format=jpg&name=small,https://pbs.twimg.com/media/G4yVXQwakAAb94i?format=jpg&name=240x240,https://pbs.twimg.com/media/G4yV0jpakAAY80w?format=jpg&name=240x240",
    "rating": 1918
  },
  {
    "tweet_datetime_str": "2025-11-03 04:56",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.cR2I.cR2I.cR2I.cxFO.dJfu.dJfu.cpC4.cpC4.cpwU.cpwU.cpwU.dhqc.dhqc.dhqc.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.dyzU.dyzU.cxFE.cxFE.cpwe.cpwe.cpwe.cphA.cphA",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "人形Nm",
    "tmatch": "Alikushia_VRC/1985073540648018044",
    "twname": "アリクシア@VRChatのすがた",
    "twitter_id": "@Alikushia_VRC",
    "twtext": "CR1540くらいから破壊ネメシスから人形ネメシスに乗り換えて9連勝きちゃ<br>EPIC行ったので今日は寝ます",
    "image_links": "https://pbs.twimg.com/media/G4xl3M6aEAA2ajD?format=jpg&name=small,https://pbs.twimg.com/media/G4xl3M4boAAdrub?format=jpg&name=small",
    "rating": 1661
  },
  {
    "tweet_datetime_str": "2025-11-03 04:24",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dO4Y.cc--.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.dJRg.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "cqcq_sv/1985065500725121104",
    "twname": "CQCQ",
    "twitter_id": "@cqcq_sv",
    "twtext": "シャドバ14連勝でCR全体1位てすごい？？？<br><br>全試合配信内で戦ってるからプレイやマリガンが気になる人は見てみてね！<br><br><a href=\"https://t.co/QesEQJ6T7W\" style=\"color: rgb(29, 155, 240);\">https://youtube.com/live/0wzlTXL4kHE?si=2pOiigGIYcV2WoTJ…</a>",
    "image_links": "https://pbs.twimg.com/media/G4xejbeaYAAhLaV?format=jpg&name=small,https://pbs.twimg.com/media/G4xejambgAApEoh?format=jpg&name=240x240,https://pbs.twimg.com/media/G4xejcGbkAAYAih?format=jpg&name=240x240",
    "rating": 1916
  },
  {
    "tweet_datetime_str": "2025-11-03 03:46",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dO4Y.cc--.dNpM.dNpM.dNpM.dO2-.dO2-.dJRg.dJRg.dJRg.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "財宝R",
    "tmatch": "YouTube_dmdm/1985055936369889773",
    "twname": "でむでむ",
    "twitter_id": "@YouTube_dmdm",
    "twtext": "ロイヤルEPICいった！！！ナイス！！",
    "image_links": "https://pbs.twimg.com/media/G4xVvNEaUAAFTBv?format=jpg&name=small,https://pbs.twimg.com/media/G4xVy9caAAAKCKo?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-03 03:39",
    "class_no": 7,
    "deck_code": ".dhLW.dhLW.dhLW.dhqm.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.cR2I.cR2I.dJfu.dJfu.dJfu.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.dhqc.dhqc.dhqc.da3k.da3k.dCK-.dCK-.dCK-.di4E.cph0.cph0.cpwe.cpwe.cpwe.dzA8.dzA8.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "人形Nm",
    "tmatch": "kamiJI_/1985054255842312285",
    "twname": "かみじー",
    "twitter_id": "@kamiJI_",
    "twtext": "バブ寄せ人形ネメで1位タッチ記念。ツヴァイとオーキスが明確なストロングポイントだから勝ち筋絞ったらしっくりきた感じ。従来のテンポ顔詰めムーブ狙いつつ、オーキス投げただけじゃ勝たなそうならバブバブオーキス改良21点orサンダル20点プランに移行すると手広く戦えて良かった",
    "image_links": "https://pbs.twimg.com/media/G4xSzH3aQAAvAqK?format=jpg&name=small,https://pbs.twimg.com/media/G4xS5WlbUAAB9nm?format=jpg&name=small",
    "rating": 1885
  },
  {
    "tweet_datetime_str": "2025-11-03 03:35",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dO4Y.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.dJRg.cdTm.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "mattsu__sv/1985053240199881198",
    "twname": "まっつ",
    "twitter_id": "@mattsu__sv",
    "twtext": "ロイヤルでビヨンド<br>ゼタ＆ベアトリクスが強すぎる～",
    "image_links": "https://pbs.twimg.com/media/G4xTGHCbEAAHxZe?format=jpg&name=small,https://pbs.twimg.com/media/G4xONyRacAAH6Cl?format=jpg&name=small",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-03 03:00",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.cc--.cdTm.cdTm.cdTm.cdWk.cdWk.cdjE.cdjE.cdjE.cxFE.cxFE.cxFE.dJRg.dJRg.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dO4Y.dO4Y.dOIc.dOIc.dOIc.dOLk.dOLk.dOLk.dOYE.dOYE.dOYE.dOYO.dOYO.dOYO.dmyk.dmyk.dmyk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "cochi_1491/1985044365220429963",
    "twname": "東風",
    "twitter_id": "@cochi_1491",
    "twtext": "<a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a><br>財宝ロイヤルで初BEYOND！！ <br>ランキングにも載ってて嬉しい！",
    "image_links": "https://pbs.twimg.com/media/G4xLUm9bsAE62so?format=jpg&name=small,https://pbs.twimg.com/media/G4xLUm-aEAAcdC-?format=jpg&name=240x240,https://pbs.twimg.com/media/G4xLUm7bQAADH03?format=jpg&name=240x240",
    "rating": 1861
  },
  {
    "tweet_datetime_str": "2025-11-03 02:49",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dO4Y.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.cdTm.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "sansation614/1985041495557279861",
    "twname": "ゆーみん",
    "twitter_id": "@sansation614",
    "twtext": "普通の財宝ロイヤルでBEYOND到達<img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f618.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f618.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f618.svg\"/><br><br>山の中にめちゃくちゃ打点埋まってるのが好きすぎる:;(∩´﹏`∩);:",
    "image_links": "https://pbs.twimg.com/media/G4xIt8gaYAAtHLb?format=jpg&name=small,https://pbs.twimg.com/media/G4xIt8faQAAy6TK?format=jpg&name=small",
    "rating": 1857
  },
  {
    "tweet_datetime_str": "2025-11-03 02:00",
    "class_no": 6,
    "deck_code": ".d9Sc.d9Sc.cmmw.cmmw.cmmw.c9hW.c9hW.cm--.dXaW.dXaW.dXaW.cnGA.cnGA.cnGA.cxFO.cxFO.cxFO.dwjk.dwjk.dwjk.dhqc.dhqc.dXdU.dXdU.dXdU.dY3c.dY3c.di4E.d9uu.d9uu.d9uu.cxFE.d9uk.d9uk.d9uk.cnUO.cnUO.cnUO.dwju.dwju",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "守護B",
    "tmatch": "gizellerxy/1985029314698682726",
    "twname": "ゆじん",
    "twitter_id": "@gizellerxy",
    "twtext": "純正守護ビショップで7連勝&amp;Epic到達‼︎<br><br>クレストだとマーフィンやら色々キープしなきゃ行けないノイズが増えるのが嫌だからこれ‼︎出してれば勝てる強い‼︎おすすめ‼︎",
    "image_links": "https://pbs.twimg.com/media/G4w9o4Ra8AAaLj9?format=jpg&name=small,https://pbs.twimg.com/media/G4w9o4PbAAAOi80?format=jpg&name=small",
    "rating": 1654
  },
  {
    "tweet_datetime_str": "2025-11-03 01:31",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfQm.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dpCU.dpCU.dpCU.cfjM.cfjM.cfjM.dhqc.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.d24u.dpP8.dpP8.dpP8.dovu.dovu.dovu.di4E.d2a8.d2a8.d2a8.d2Z-.d2Z-.d2Z-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "秘術W",
    "tmatch": "huwatororo1995/1985021892076667255",
    "twname": "じ",
    "twitter_id": "@huwatororo1995",
    "twtext": "秘術ウィッチでEPIC！",
    "image_links": "https://pbs.twimg.com/media/G4w24hZaQAA6inx?format=jpg&name=small,https://pbs.twimg.com/media/G4w24hSaAAAkhy8?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-03 01:29",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dhqm.dhqm.dhqm.cEpU.cEpU.cdEI.cdEI.cdEI.c_uG.c_uG.c_uG.dmDs.dmDs.dmDs.cdTm.cdTm.cdTm.cdjY.dmTe.dmTe.dmTe.cdTw.cdTw.cdTw.dmyk.dmyk.dmyk.cdE8.cdE8.cdE8.cdjE.cdjE.cdjE.cxFE.cxFE.cxFE.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "アグロR",
    "tmatch": "dqx_leaf/1985021466124108240",
    "twname": "りぃふ",
    "twitter_id": "@dqx_leaf",
    "twtext": "ロイヤルもULTIMATEまできた！<br>財宝あんまり勝てなかったからアグロロイヤル組んでみたらめっちゃ勝てる！ケンタ入れるよりルリアでオーディン確定にしたほうが絶対強い！<br>後、御者めちゃくちゃ強かったから3にするのもありかも？<br>勝っても負けても5分くらいで終わるから精神衛生的にもとても良き",
    "image_links": "https://pbs.twimg.com/media/G4w2gO6bgAAYCJN?format=jpg&name=360x360,https://pbs.twimg.com/media/G4w2gPZb0AAlmLg?format=jpg&name=360x360",
    "rating": 1754
  },
  {
    "tweet_datetime_str": "2025-11-03 01:24",
    "class_no": 4,
    "deck_code": ".dTEE.dTEE.cJSM.cJSM.d50E.d50E.d50E.d4KU.d4KU.d4KU.dJfu.ciMG.ciMG.ciMG.dSxe.dSxe.cJl6.cJl6.cJl6.d4X8.d4X8.d4X8.dTQu.dTQu.dTQu.drrO.drrO.cibu.cibu.cibu.cxFE.cxFE.cxFE.d4mc.d4mc.drrE.drrE.cic2.cic2.cic2",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "疾走ランプD",
    "tmatch": "Anne_hanakopoyo/1985020084872757623",
    "twname": "花小泉",
    "twitter_id": "@Anne_hanakopoyo",
    "twtext": "ドラゴンさん BEYONDきちゃ〜",
    "image_links": "https://pbs.twimg.com/media/G4w1O9QasAAAEyp?format=jpg&name=small,https://pbs.twimg.com/media/G4w1O-PbAAEWWK-?format=jpg&name=240x240,https://pbs.twimg.com/media/G4w1O-0aQAA1sJs?format=jpg&name=240x240",
    "rating": 1852
  },
  {
    "tweet_datetime_str": "2025-11-03 01:07",
    "class_no": 3,
    "deck_code": ".cH3E.cH3E.cH3E.cfTu.cfTu.cfTu.d2NU.d2NU.dpCU.dpCU.dpCU.cYOc.dpO-.dpO-.dpO-.cfjM.cfjM.cfy-.cfy-.cfy-.cg9e.cg9e.cg9e.d24k.d24k.d2a8.d2a8.cxFE.cg9U.cg9U.cg9U.cfz8.cfz8.cfz8.cHFu.cHFu.cHFu.cgCc.cgCc.cgCc",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "スペルW",
    "tmatch": "Kamishimosabaki/1985016021703655676",
    "twname": "＊",
    "twitter_id": "@Kamishimosabaki",
    "twtext": "atom式スペルWで一旦ultimateまで<br>秘術はやり口が知れ渡りすぎてあんま勝率出ず",
    "image_links": "https://pbs.twimg.com/media/G4wxAY2aUAExApE?format=jpg&name=360x360,https://pbs.twimg.com/media/G4wxULPbQAAm62W?format=jpg&name=360x360",
    "rating": 1754
  },
  {
    "tweet_datetime_str": "2025-11-03 01:00",
    "class_no": 3,
    "deck_code": ".cfTu.cfTu.cfTu.cH1g.cH1g.cH1g.cwZU.cwZU.cfQm.cfQm.d1r6.d1r6.d1r6.dpCU.cfjM.cfjM.cfjM.cfy-.cfy-.cfy-.cg9e.cg9e.cg9e.d24k.d24k.d2a8.d2a8.d2a8.cg9U.cg9U.cg9U.cfz8.cfz8.cfz8.cfjW.cfjW.cYqu.cgCc.cgCc.cgCc",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "秘術スペルW",
    "tmatch": "gmkzdesuyo/1985014034081743106",
    "twname": "くらげ",
    "twitter_id": "@gmkzdesuyo",
    "twtext": "やっとEPICおかえりした…。<br>サタン入りウィッチの正解を誰か教えて欲しい…。<br>使うなってことなのかも知らん。",
    "image_links": "https://pbs.twimg.com/media/G4wvvaYbgAA78X3?format=jpg&name=small,https://pbs.twimg.com/media/G4wvvaabEAAvG9X?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-03 00:32",
    "class_no": 7,
    "deck_code": ".cQnG.cQnG.cQnG.cR2I.cpC4.cpC4.cpC4.cpRO.cpRO.cpRO.cph0.cph0.cpwU.cpwU.cpwU.cpwe.cpwe.cpwe.cxFE.cxFE.dBcG.dBcG.dBcG.dCK-.dCK-.dCK-.da3k.dhLW.dhLW.dhLW.dhqc.dhqc.dhqc.dhqm.dyzU.dyzU.dz9-.dz9-.dzA8.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "人形Nm",
    "tmatch": "FCuisan67600/1985007231428096041",
    "twname": "翡翠@デイリー勢",
    "twitter_id": "@FCuisan67600",
    "twtext": "<a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a><br>人形ネメシスで７連勝してEPICへ",
    "image_links": "https://pbs.twimg.com/media/G4wo_HBbAAEnST_?format=jpg&name=small,https://pbs.twimg.com/media/G4wpB0Gb0AAoyOj?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wpVSCasAAS6mv?format=jpg&name=240x240",
    "rating": 1674
  },
  {
    "tweet_datetime_str": "2025-11-03 00:14",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dO4Y.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.cdTm.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk.cdWk.dmyk.dmyk.dmyk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "skyline19910530/1985002580909736350",
    "twname": "楯無さん@元ニコ生主",
    "twitter_id": "@skyline19910530",
    "twtext": "初のビヨンド！<br>瞬間7位まで行った！<br>まあ財宝強い！<br><a href=\"https://x.com/hashtag/シャドバ?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバ</a><br><a href=\"https://x.com/hashtag/ビヨンド?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#ビヨンド</a>",
    "image_links": "https://pbs.twimg.com/media/G4wlUZpbsAE-VzM?format=jpg&name=small,https://pbs.twimg.com/media/G4wlUZoa0AA5jkC?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wlUZybcAA_bHb?format=jpg&name=240x240",
    "rating": 1865
  },
  {
    "tweet_datetime_str": "2025-11-03 00:14",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dpCU.dpCU.dpCU.dJfu.dJfu.cfjM.cfjM.cfjM.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.dovu.dovu.dovu.di4E.di4E.d2a8.d2a8.d2Z-.d2Z-.d2Z-.dQ-e",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "秘術W",
    "tmatch": "Melon_71/1985002546705183056",
    "twname": "Melon",
    "twitter_id": "@Melon_71",
    "twtext": "秘術ウィッチでBEYOND来た！<br>初めて踏めたからガチ嬉しい<br>財宝ロイヤルと人形ネメシス以外にはあんまり負けなかった<br>ギルネが細かい回復とか足りない打点の一押しに良すぎる<br><a href=\"https://x.com/hashtag/シャドバ?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバ</a><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4wlS4YbAAAdudn?format=jpg&name=small,https://pbs.twimg.com/media/G4wlS44a4AA_SBJ?format=jpg&name=360x360,https://pbs.twimg.com/media/G4wlS__bEAAOMyH?format=jpg&name=360x360",
    "rating": 1860
  },
  {
    "tweet_datetime_str": "2025-11-03 00:12",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.cc--.cdEI.cdEI.cdEI.c_uG.c_uG.c_uG.dNpM.dNpM.dNpM.c_hc.c_hc.cxFO.cdTm.cdTm.cdTm.dmTe.dmTe.dmTe.cdTw.cdTw.cdTw.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dmmE.cxFE.cxFE.cxFE.cdWk.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "アグロR",
    "tmatch": "KJ_SSBU/1985002093472883165",
    "twname": "Kamijames",
    "twitter_id": "@KJ_SSBU",
    "twtext": "今期もロイヤルULTIMATE到達！<br>アグロと財宝を気分で使い分けました！<br>財宝のパワーは言わずもがな、アグロもテンポ遅いデッキ、ミラー(対財宝)に対して強く出れるからいいデッキだと思う！<br><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a><br><a href=\"https://x.com/hashtag/シャドバ勢と繋がりたい?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバ勢と繋がりたい</a>",
    "image_links": "https://pbs.twimg.com/media/G4wk4YWbQAAEAyl?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wk4YcbUAAaqKT?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wk4YWbgAEqoZc?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wk4YZbMAAXT7M?format=jpg&name=240x240",
    "rating": 1762
  },
  {
    "tweet_datetime_str": "2025-11-03 00:12",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.dJRg.cdTm.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "財宝R",
    "tmatch": "KJ_SSBU/1985002093472883165",
    "twname": "Kamijames",
    "twitter_id": "@KJ_SSBU",
    "twtext": "今期もロイヤルULTIMATE到達！<br>アグロと財宝を気分で使い分けました！<br>財宝のパワーは言わずもがな、アグロもテンポ遅いデッキ、ミラー(対財宝)に対して強く出れるからいいデッキだと思う！<br><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a><br><a href=\"https://x.com/hashtag/シャドバ勢と繋がりたい?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバ勢と繋がりたい</a>",
    "image_links": "https://pbs.twimg.com/media/G4wk4YWbQAAEAyl?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wk4YcbUAAaqKT?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wk4YWbgAEqoZc?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wk4YZbMAAXT7M?format=jpg&name=240x240",
    "rating": 1762
  },
  {
    "tweet_datetime_str": "2025-11-02 23:33",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.cR2I.cR2I.cR2I.dJQ6.dJfu.dJfu.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.dhqc.dhqc.dhqc.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.dyzU.dyzU.cxFE.cxFE.cxFE.cpwe.cpwe.cpwe.cphA.cphA",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "人形Nm",
    "tmatch": "aqours0321/1984992276641423867",
    "twname": "アクア",
    "twitter_id": "@aqours0321",
    "twtext": "人形ネメシスでビヨンド",
    "image_links": "https://pbs.twimg.com/media/G4wbxIYacAEBfiJ?format=jpg&name=small,https://pbs.twimg.com/media/G4wbyFua0AA25Lt?format=jpg&name=small",
    "rating": 1859
  },
  {
    "tweet_datetime_str": "2025-11-02 23:23",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dpCU.dpCU.dpCU.dJfu.dJfu.cfjM.cfjM.cfjM.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.dovu.dovu.dovu.di4E.d2a8.d2a8.d2a8.cxFE.cxFE.d2Z-.d2Z-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "秘術W",
    "tmatch": "OxuKiEiwkjbVXqa/1984989656929493014",
    "twname": "ころまる",
    "twitter_id": "@OxuKiEiwkjbVXqa",
    "twtext": "シャドバ、レートそんな高く無いけどグラマス秘術で9連勝<br>ライオは出せても勝たないのでオーディンで後一歩を押し込み<br>tier1の強さかと言われると微妙でtier1.5な感想",
    "image_links": "https://pbs.twimg.com/media/G4wZkhja4AADUbB?format=jpg&name=small,https://pbs.twimg.com/media/G4wZkhcbQAEf3p-?format=jpg&name=small",
    "rating": 1659
  },
  {
    "tweet_datetime_str": "2025-11-02 23:07",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.dhqm.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.cR2I.cR2I.cR2I.dJfu.dJfu.cpC4.cpC4.cpwU.cpwU.cpwU.dhqc.dhqc.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.dyzU.dyzU.cxFE.cxFE.cxFE.cpwe.cpwe.cpwe.cphA.cphA",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "人形Nm",
    "tmatch": "kryn_zoo/1984985680469250554",
    "twname": "くらやん† ໒꒱",
    "twitter_id": "@kryn_zoo",
    "twtext": "人形ネメシス強すぎて一瞬でアルティメット到達<br>1600から一回しか負けずにアルティメットこれたのは流石にデッキの強さを認めざるを得ない<br>12-1",
    "image_links": "https://pbs.twimg.com/media/G4wV9B5b0AAnM5w?format=jpg&name=small,https://pbs.twimg.com/media/G4wV9BxbIAAMhzP?format=jpg&name=small",
    "rating": 1750
  },
  {
    "tweet_datetime_str": "2025-11-02 22:44",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.dBrk.dBrk.dBrk.cR2I.cR2I.dJfu.dJfu.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.cYeE.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.cxFE.cxFE.cpwe.cpwe.cpwe.cphA.cphA.cphA.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "人形Nm",
    "tmatch": "kuroshiro7793/1984979825447330034",
    "twname": "クロ",
    "twitter_id": "@kuroshiro7793",
    "twtext": "人形ネメシスでEPICまでいけた。守護ビショ相手にまだ無敗<br>そのまま人形の動きで攻めても強いしベルゼバブ挟んでOTK並みの打点出しても強い<br>財宝相手にはオーキスごり押しで五分主張",
    "image_links": "https://pbs.twimg.com/media/G4wPXmZb0AA0mGP?format=jpg&name=small,https://pbs.twimg.com/media/G4wPZTzbUAAFk92?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-02 22:28",
    "class_no": 4,
    "deck_code": ".d4HW.d4HW.d4HW.dTEE.dTEE.dTEE.dhqm.dhqm.d50E.d50E.d50E.d4KU.d4KU.d4KU.ciMG.ciMG.ciMG.dSxe.dSxe.cJl6.cJl6.cJl6.dTQu.dTQu.dTQu.drrO.drrO.drrO.cibu.cibu.cibu.cxFE.cxFE.cic2.cic2.cic2.dTQk.dTQk.ciM6.ciM6",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "疾走ランプD",
    "tmatch": "SANA_1323thanks/1984976020085379094",
    "twname": "Asatsuyu（SANA）",
    "twitter_id": "@SANA_1323thanks",
    "twtext": "ウィルナス抜きドロー盛り盛りランプドラゴンで一旦ULTIMATE到達",
    "image_links": "https://pbs.twimg.com/media/G4wMXdCagAEzrxo?format=jpg&name=small,https://pbs.twimg.com/media/G4wMYwObcAABVrC?format=jpg&name=small",
    "rating": 1760
  },
  {
    "tweet_datetime_str": "2025-11-02 21:47",
    "class_no": 7,
    "deck_code": ".dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.dyRG.daY-.daY-.daY-.daHo.daHo.daHo.dJfu.cpwU.dalU.dalU.dalU.dyjs.dyjs.dhqc.dhqc.da0c.da0c.dale.dale.dale.cph0.cph0.daVs.daVs.daVs.dyzU.dyzU.cxFE.cxFE.dzA8.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "リーシェナNm",
    "tmatch": "h4sp1_/1984965701229318464",
    "twname": "はすぴ",
    "twitter_id": "@h4sp1_",
    "twtext": "純破壊ネメシスでEPIC行けました〜<img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f4af.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f4ae.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f331.svg\"/><br><br>高コストかさばるとしんどいから、祈祷者とか入れてミラーのベルゼバブメンコに対して<img src=\"https://abs-0.twimg.com/emoji/v2/svg/1f362.svg\"/>卵取り祈祷者超進化の択を入れても良さそうかもと検討中だけど、低コスト増やしたとて卵依存は変わらないのでこれで良いかな",
    "image_links": "https://pbs.twimg.com/media/G4wDx68bkAEfTQ5?format=jpg&name=360x360,https://pbs.twimg.com/media/G4wDx7EaoAALIdC?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wDx7CawAA4D9x?format=jpg&name=240x240",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-02 21:41",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.cEZs.dOLk.dOLk.dOLk.dO4Y.dO4Y.cc--.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJfu.dJRg.dJRg.cdTm.cdTm.dOYO.dOYO.dOYO.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.dOYE.dOYE.dOYE.cxFE.cxFE.cxFE.cdWk.cdWk",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "財宝R",
    "tmatch": "hiiroscarlet_sv/1984964163467350409",
    "twname": "律",
    "twitter_id": "@hiiroscarlet_sv",
    "twtext": "財宝ロイヤルで全クラスCR瞬間1位達成〜！！<br><br>構築や石板についてはnote書いているのでそちらをどうぞ！<br><br>なんの実績もない私だし、この後猛者たちに抜かされるの分かってるのでいい思い出出来ました！笑<br><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4wCYlxbEAA915M?format=jpg&name=small,https://pbs.twimg.com/media/G4wCYlxbIAE6Dzw?format=jpg&name=small",
    "rating": 1913
  },
  {
    "tweet_datetime_str": "2025-11-02 21:32",
    "class_no": 5,
    "deck_code": ".dhqm.dhqm.dhqm.cLuw.cLuw.cLuw.ckYk.ckYk.ckYk.ckrU.ckrU.ckrU.d6mk.d6mk.d6mk.dJfu.dJfu.dJfu.d6zE.d6zE.d6zE.dhqc.dhqc.dhqc.cl2I.cl2I.cl2I.dVdM.dVdM.dVdM.dtYm.cxFE.cxFE.cxFE.dVt8.dVt8.dVt8.cl1-.cl1-.cl1-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "ミッドレンジNi",
    "tmatch": "gara4poke_2nd/1984961786223931600",
    "twname": "ガラシさぶ",
    "twitter_id": "@gara4poke_2nd",
    "twtext": "バザラガ採用型ミッドレンジナイトメア8連勝でBEYOND到達！現在5位！<br><br>従来であれば不利対面のモードメアと進化メアにはオーディンが採用されないため、バザラガ設置できれば除去されずに相性差をひっくり返せます！<br><br><img src=\"https://abs-0.twimg.com/emoji/v2/svg/2b07.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/2b07.svg\"/>デッキリストは3枚目<img src=\"https://abs-0.twimg.com/emoji/v2/svg/2b07.svg\"/><img src=\"https://abs-0.twimg.com/emoji/v2/svg/2b07.svg\"/><br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4wAOUAaIAAO3hw?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wAOZbaQAAeiRW?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wAOZha4AEQQDp?format=jpg&name=240x240,https://pbs.twimg.com/media/G4wAOcaawAAMly3?format=jpg&name=240x240",
    "rating": 1857
  },
  {
    "tweet_datetime_str": "2025-11-02 21:17",
    "class_no": 4,
    "deck_code": ".dhLW.dhLW.dhLW.dhqm.dhqm.dhqm.d4KU.d4KU.d4KU.dJfu.ciMG.ciMG.ciMG.dSxe.dSxe.dSxe.cJl6.cJl6.cJl6.dhqc.dhqc.dhqc.drL-.drL-.drL-.drrO.drrO.drrO.di4E.di4E.di4E.cibu.cibu.cYqk.cYqk.cYqk.cxFE.drM8.drM8.drM8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 6,
    "deck_name": "進化D",
    "tmatch": "serrrrrata/1984957939493536088",
    "twname": "せらーた",
    "twitter_id": "@serrrrrata",
    "twtext": "進化ドラゴンでEPIC行ったぞ！<br>フォルテ使ったことないし変えた方がいいかも",
    "image_links": "https://pbs.twimg.com/media/G4v8uVRa0AAtqwL?format=jpg&name=small,https://pbs.twimg.com/media/G4v8uVQbMAAxnsn?format=jpg&name=small",
    "rating": 1650
  },
  {
    "tweet_datetime_str": "2025-11-02 20:46",
    "class_no": 5,
    "deck_code": ".dhqm.dhqm.dhqm.cLuw.cLuw.cLuw.ckrU.ckrU.ckrU.d6mk.d6mk.d6mk.dJfu.dJfu.d6zE.d6zE.d6zE.dtoY.dtoY.dtoY.dVNk.dVNk.dVNk.cl2I.cl2I.cl2I.dVdM.dVdM.dVdM.dtYm.dtYm.cxFE.cxFE.cxFE.dVt8.dVt8.dVt8.cl1-.cl1-.cl1-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "ミッドレンジNi",
    "tmatch": "mizuni00/1984950351649546737",
    "twname": "水煮/横浜F・マリノス",
    "twitter_id": "@mizuni00",
    "twtext": "ナイトメアBEYOND〜<br>3つのアーキを色々試して最後はミッドナイトメアで到達！<br>バアルが序盤支えてくれるのと先2ルリア先3バアルが強い<br>バザラガはきっとララアンセム",
    "image_links": "https://pbs.twimg.com/media/G4v1018aEAATyh3?format=jpg&name=small,https://pbs.twimg.com/media/G4v103daYAAz0H8?format=jpg&name=small",
    "rating": 1850
  },
  {
    "tweet_datetime_str": "2025-11-02 19:49",
    "class_no": 3,
    "deck_code": ".cH1g.cH1g.cH1g.cfQm.cfQm.cfQm.cfw0.cfw0.cfw0.d1r6.d1r6.d1r6.dpCU.dpCU.dpCU.cfjM.cfjM.cfjM.dhqc.dhqc.cfwA.cfwA.cfwA.d24u.d24u.dpP8.dpP8.dpP8.dovu.dovu.di4E.di4E.d2a8.d2a8.d2a8.cxFE.cxFE.d2Z-.d2Z-.d2Z-",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "秘術W",
    "tmatch": "i_games_n/1984935992382587098",
    "twname": "ni ru",
    "twitter_id": "@i_games_n",
    "twtext": "秘術ウィッチ一旦アルティメット<br>ピン刺しライオは抜いた方が良いと思った<br>30戦やって相手に一度もビショがいない環境から消えた<br>秘術ウィッチ、マリガンが1番むずい",
    "image_links": "https://pbs.twimg.com/media/G4voxABaQAAu8nu?format=jpg&name=small,https://pbs.twimg.com/media/G4voxA1aAAEf1dZ?format=jpg&name=small",
    "rating": 1759
  },
  {
    "tweet_datetime_str": "2025-11-02 19:38",
    "class_no": 2,
    "deck_code": ".cEZs.cEZs.dOLk.dOLk.dOLk.dNpM.dNpM.dNpM.dO2-.dO2-.dO2-.dJRg.dJRg.cdTm.cdTm.cdTm.dOYO.dOYO.dOYO.dmEA.dOIc.dOIc.dOIc.dmyk.dmyk.dmyk.cdjE.cdjE.cdjE.cxFE.cxFE.cxFE.cdWk.cdWk.dO4Y.dO4Y.dO4Y.dOYE.dOYE.dOYE",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 7,
    "deck_name": "財宝R",
    "tmatch": "tomomaru102/1984933206521700676",
    "twname": "とも。",
    "twitter_id": "@tomomaru102",
    "twtext": "財宝ロイヤルで9連勝してアルティメットまで来ました！今期も序盤元気！",
    "image_links": "https://pbs.twimg.com/media/G4vmOvubcAAqru1?format=jpg&name=small,https://pbs.twimg.com/media/G4vmOvtbUAA-dcb?format=jpg&name=240x240,https://pbs.twimg.com/media/G4vmOvua0AAklke?format=jpg&name=240x240",
    "rating": 1754
  },
  {
    "tweet_datetime_str": "2025-11-02 18:57",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.dBcG.dhqm.dhqm.dhqm.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.dBrk.dBrk.cR2I.cR2I.cR2I.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.dhqc.dhqc.dhqc.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.cxFE.cxFE.cxFE.cpwe.cpwe.cpwe.dzA8.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "人形Nm",
    "tmatch": "mizutan521913/1984922814567366967",
    "twname": "すだれ",
    "twitter_id": "@mizutan521913",
    "twtext": "人形ネメシスでBEYOND到達！<br>オーキス1回の打点を上げたかったのでノアとベルゼバブを入れてます<br>今の環境だとツヴァイが鬼のように強い！<br><a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a>",
    "image_links": "https://pbs.twimg.com/media/G4vcxw-aoAAeg6o?format=jpg&name=small,https://pbs.twimg.com/media/G4vcxw8aIAA1vGs?format=jpg&name=small",
    "rating": 1856
  },
  {
    "tweet_datetime_str": "2025-11-03 12:33",
    "class_no": 7,
    "deck_code": ".dBcG.dBcG.cQnG.cQnG.cQnG.cpRO.cpRO.cpRO.cR2I.cR2I.dJfu.dJfu.cpC4.cpC4.cpC4.cpwU.cpwU.cpwU.dhqc.dhqc.da3k.da3k.dCK-.dCK-.dCK-.cpRY.cpRY.cpRY.cph0.cph0.cxFE.cxFE.cxFE.cpwe.cpwe.cpwe.cphA.cphA.dzA8.dzA8",
    "ren_count": 0,
    "rank_no": 0,
    "group_no": 9,
    "deck_name": "人形Nm",
    "tmatch": "guiltus_/1985188593451843899",
    "twname": "4÷÷6822・69?f",
    "twitter_id": "@guiltus_",
    "twtext": "ネメ瞬間1位さらに更新！<br>今期初めてランキング乗ったけど1900更新で激アツすぎ！リストもちょっと枚数いじったので再掲<br>全クラスで見ても瞬間4位！<br> <a href=\"https://x.com/hashtag/シャドバWB?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバWB</a> <a href=\"https://x.com/hashtag/シャドバ勢と繋がりたい?src=hashtag_click\" style=\"color: rgb(29, 155, 240);\">#シャドバ勢と繋がりたい</a>",
    "image_links": "https://pbs.twimg.com/media/G4zN_J5bEAAxLtP?format=jpg&name=small,https://pbs.twimg.com/media/G4zOF0hbAAAmRSv?format=jpg&name=small",
    "rating": 1909
  }
];
allTweets = allTweets || [];
allTweets.push(...tweets);
